import Assessment from "../models/Assessment.js";
import Roadmap from "../models/Roadmap.js";
import { generateRoadmap } from "../ai/agent/tools/roadmapTool.js";

export const generateRoadmapFromAssessment = async (req, res) => {
  try {
    const { assessmentId } = req.params;

    const assessment = await Assessment.findOne({
      _id: assessmentId,
      user: req.user._id,
    });

    if (!assessment) {
      return res.status(404).json({
        success: false,
        message: "Assessment not found",
      });
    }

    if (assessment.status !== "completed") {
      return res.status(400).json({
        success: false,
        message: "Assessment must be completed first",
      });
    }

    if (!assessment.result?.level) {
      return res.status(400).json({
        success: false,
        message: "Assessment result is incomplete",
      });
    }

    const roadmap = await generateRoadmap({
      domain: assessment.domain,
      subdomain: assessment.subdomain,
      goal: assessment.goal,
      level: assessment.result.level,
      skillScores: assessment.result.skillScores,
    });

    if (
      !roadmap ||
      !Array.isArray(roadmap.skills) ||
      !Array.isArray(roadmap.weeks)
    ) {
      return res.status(500).json({
        success: false,
        message: "Invalid roadmap generated by AI",
      });
    }

    const savedRoadmap = await Roadmap.create({
      user: req.user._id,
      assessment: assessment._id,
      domain: assessment.domain,
      subdomain: assessment.subdomain,
      goal: assessment.goal,
      level: assessment.result.level,
      skills: roadmap.skills,
      weeks: roadmap.weeks,
      status: "generated",
    });

    return res.status(201).json({
      success: true,
      roadmap: savedRoadmap,
    });
  } catch (error) {
    console.error("Roadmap generation error:", error);

    return res.status(500).json({
      success: false,
      message: error.message,
    });
  }
};

export const getMyRoadmaps = async (req, res) => {
  try {
    const roadmaps = await Roadmap.find({
      user: req.user._id,
    }).sort({ createdAt: -1 });

    return res.json({
      success: true,
      roadmaps,
    });
  } catch (error) {
    console.error("Get roadmaps error:", error);

    return res.status(500).json({
      success: false,
      message: error.message,
    });
  }
};

export const getRoadmapById = async (req, res) => {
  try {
    const { roadmapId } = req.params;

    const roadmap = await Roadmap.findOne({
      _id: roadmapId,
      user: req.user._id,
    });

    if (!roadmap) {
      return res.status(404).json({
        success: false,
        message: "Roadmap not found",
      });
    }

    return res.json({
      success: true,
      roadmap,
    });
  } catch (error) {
    console.error("Get roadmap error:", error);

    return res.status(500).json({
      success: false,
      message: error.message,
    });
  }
};